### ISSUE TITLE
Details on how to use it

### ISSUE THREAD

**Issue by YouweiUSC** [rowan-walsh/CFD-Bayesian-Optimization#1]
Could you provide more details on how to use this repo to carry out the ANSYS-based optimization?
what should be prepared to start the optimization? the limitation or capability of the CFX simulation?

**Comment by rowan-walsh** [comment]
Hi @YouweiUSC, thanks for your interest 😃. It has been a long time since I last worked with this repo so I'll need to dredge through some old memories, please bear with me if there are any mistakes. It also seems like I've lost the original scripts I had that made use of this repo (didn't take a backup of my university computer with me), so unfortunately I don't have an example to give you.

## Using this Repo

This repo was a bit of a hack job to automate simulating the performance of hydro turbines in ANSYS workbench (v17.1). I wanted to have an optimization algorithm choose the next turbine geometry to simulate and I didn't want to use one of ANSYS's built-in algorithms. I also wanted to have the simulations run around the clock without needing me to manually enter the optimization's next suggested geometry parameters into ANSYS WB and run the simulations.

The entry point to use this repo would be to create an instance of the [@MOSAO](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/blob/master/%40MOSAO/MOSAO.m) class and then use its `initialize`, `run`, and `continue_run` methods. The code in the [`validate_options`](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/blob/master/%40MOSAO/validate_options.m) private method can give you some idea as to what options are available for the optimization algorithm. The `functionHandle` parameter of the `MOSAO` constructor is important: this is the handle to the "black-box" function that the algorithm will attempt to optimize.

In my case I added the [@WBpackage](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/blob/master/%40WBpackage/WBpackage.m) class to stand in as this "black-box" function by dispatching simulations in ANSYS workbench (see below). For example, after creating an instance of `WBpackage` called `WBpack`, it could be used for the `MOSAO` constructor's `functionHandle` parameter with the form `@(x) WBpack.simulate(x, 'seek')`. But really any other function with the right form could be optimized here.

## Generalizing from this Repo

Ideally this repo should generalize to any ANSYS workbench setup you have that uses the design points table to parameterize your simulations (some amount of input parameters drive the geometry and/or simulation, and some amount of output parameters to optimize are calculated from the simulation results). That being said, MATLAB is pretty clunky and if I was doing this work again today I would likely use Python; it looks like it has a few Bayesian optimization packages out now.

The most useful aspect of this repo now might be as a demonstration that it is **possible** to use a design-points-table-driven ANSYS workbench project as the "black box function" for an optimization algorithm. This was done with the [@WBinstance](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/tree/master/%40WBinstance) class. It would build (line-by-line) an IronPython script to execute with an ANSYS workbench project, and then interpret any result files output by the script. The script was generated on the fly to do things like:

-  Save the data from previously-simulated design points in the WB project's design point table to a file and then retrieve the values so they could be used by the next iteration of the optimization algorithm.
- Add new design points to the WB project (based on the optimization algorithm's suggested next point to sample) and then have ANSYS WB run a simulation of the new point.
- Save and import any log messages from the simulation, to parse and check for any errors. This was important, because certain geometries suggested by the optimization were not physically possible (self-intersection, etc). The optimization algorithm needed to treat these points in the parameter space differently from points that gave valid results.

## Bayesian Optimization

If you are looking to do something similar with automating an optimization+simulation loop with ANSYS then the [@WBinstance](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/tree/master/%40WBinstance) class could be a useful place to start.

There are some possibly-helpful diagrams on the setup in my thesis (https://hdl.handle.net/1807/97656), section 4. If you're interested in Bayesian optimization for fluid simulations in particular then the other methods mentioned there could be helpful too. Michael Gelbart's thesis on Bayesian optimization (http://nrs.harvard.edu/urn-3:HUL.InstRepos:17467236) was an especially good resource for me, if you haven't already run across it.

**Comment by liptonfred** [comment]
Dear @rowan-walsh,
I am quite interested in this integration (BO + CFD) recently and I wonder that if this project could work with ANSYS Fluent? 
Best Regards,

**Comment by rowan-walsh** [comment]
Hi @liptonfred,
Yes it would work with ANSYS Fluent. You will need to have the dimensions of the geometry be driven by values in a design point table in ANSYS Workbench. And then also have the results from your Fluent simulation (ideally 1-2 calculated values: pressure drop, efficiency, etc) also be included in the design point table.

**Comment by rowan-walsh** [comment]
Updated the README  ([53a7205](https://github.com/rowan-walsh/CFD-Bayesian-Optimization/commit/53a7205f5650933bfc08c86c5cda02786969f4b8)) with info from this issue so it is more visible, closing.
